### ISSUE TITLE
v2.0

### ISSUE THREAD

**Issue by knutole** [medvirkelighet/ionic-app#1]
## Framework
- [x] Ionic framework
- [x] Mapbox GL JS (not native)
- [x] Firebase?

## todo
- [ ] add Q page
- [ ] add admin console on web (for blog + suggestions + Q's, etc)
- [ ] 

## Customizing GUI
- [ ] Web UI page for customizing entire app, for use by app creator. 
- [ ] Colors, text, language, geojson, map position, map layers, social media, app icon.

Potential customizations:
- hvilken type knapp for å legge inn innlegg (inkl. bare et ikon for å vise sted, uten tekst..)
- kategorier for innlegg
- ikoner for kategorier

## server side
- kan vi bare ha en server-less server-side? 
- hva trengs? 
- DB
- webserver... for nettversjon... men statisk html er nok? 
- push notifications for nye innlegg
- login / anon login
- [ ] firebase

## Client
- [ ] Bedre deling til sosiale medier. For eksempel et vindu som dukker opp når man har lagt inn forslag, som foreslår å dele direkte på Facebook. "Del på Facebook og få andre til å støtte opp om ditt forslag!"
- [ ] Implementere at forslagene blir "stemt på" gjennom Facebook likes, eventuelt en lokal stemmeknapp.
- [ ] Bedre offline tilgang. Laste ned bakgrunnskartet og lagre på mobil. Synce forslag når man kommer online igjen.
- [ ] Oversiktlig liste over forslag som brukere kan se på også, ikke bare admins.
